### ISSUE TITLE
Markup snippets dont work in ST3 as expected (automatically)

### ISSUE THREAD

**Issue by powrie** [uikit/uikit-sublime#11]
Markup snippets dont automatically show in ST3 unless you have the cursor within an angle bracket either empty <> or with something <div...> in it... 

if you start typing 'ui..' outside of the brackets nothing happens unless you hit ctrl+space staright away.

**Comment by florianletsch** [comment]
I've had a look at this and I can't seem to find an issue at the moment. Maybe you don't like the default behaviour? ;)

Just to clarify: Where snippets trigger is not determined by the plugin but by Sublime Text itself. Sublime Text's default behaviour is exactly like you describe it. 

If you want to have snippets appear automatically in every location of your html document (without having to hit `ctrl+space`, you can add `meta.html` to your settings' `auto_complete_selector`. 

More specifically, just add the following line to your Sublime User Settings:

```   
"auto_complete_selector": "source - comment, meta.tag - punctuation.definition.tag.begin, text.html"
```

**Comment by powrie** [comment]
OK thanks will try changing user settings. Its curious though as the behaviour i described is only effecting autocomplete for UI snippets. I dont have to do the ctrl +space for automplete for the other two forms of autocomplete. So when I type uk- within a class attribute or data- it does it automatically. If I type uikit within an open < it works too.

**Comment by florianletsch** [comment]
Yup, this is because ST3 has the following line in its default settings. I guess this is so that the default suggestion for html tags work without having to hit ctrl+space.

```js
    // Additional situations to trigger auto complete
    "auto_complete_triggers": [ {"selector": "text.html", "characters": "<"} ],
```

What I guess could be changed though, is that the snippets do not trigger when inside `<>` brackets. They do not really make sense there.
