### ISSUE TITLE
UIkit autocomplettion for Markup snippets not working

### ISSUE THREAD

**Issue by DerBeni** [uikit/uikit-sublime#14]
Hi,
...i just noticed: the autocompletion for markup snippets is not working for me :( Do you have any suggestion? Maybe a conflict with another package?

**Comment by florianletsch** [comment]
Can you please specify "not working"?

Please make sure of the following: In order for the suggestions to appear, your document needs to have the syntax set to HTML (or any child syntax like HTML (PHP)). You can set the syntax from the menu View > Syntax or via the Command Palette.

Also, have a look at the Sublime Text Console and scroll up. It should display if the extension has been loaded successfully.

**Comment by DerBeni** [comment]
Hi Florian,
...when typing in "uikit" somewhere in the document, the window with uikit components doesn't show up. The syntax is set to HTML, autocompletion for data attributes and classes is working fine.

**Comment by Riddler84** [comment]
I have a similar problem. i want to edit wordpress templates and the uikit snippets only works between the php brackets, but not in the html parts of the document.

**Comment by rogeriomarques** [comment]
Not working for me either, same as described by @DerBeni  and @Riddler84.

**Comment by wacala** [comment]
The same here, but I found that if your type "uikit" and press Tab key after (as suggest the Snippet option) it shows the context menu with components.

**Comment by Iqlaas** [comment]
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./main.py", line 3, in <module>
    from .completions import classes, attributes
ValueError: Attempted relative import in non-package

Hi there. Does this mean its not working ? Got this error when trying to install through Package Controller.

**Comment by floriandotpy** [comment]
@Iqlaas No, that looks like a different problem. Can you please open a new ticket for that? Please also provide details about your OS and which version of Sublime you're using, thanks.

**Comment by Iqlaas** [comment]
done @florianletsch :)

**Comment by floriandotpy** [comment]
Markup snippets for UIkit 3 have not been added. If we manage to prepare some snippets in the future, we will probably re-implement this. As this is not relevant at the moment, I am closing this.
