### ISSUE TITLE
Support for UIkit 2 markup?

### ISSUE THREAD

**Issue by ghost** [uikit/uikit-sublime#15]
I think in the last update some classes were lost. At least uk-container-center does not appear.
Thank you.

**Comment by ghost** [comment]
Oh, the latest update is for uikit 3, what happens with the autocomplete of uikit 2?

**Comment by floriandotpy** [comment]
You're right. The plugin is kept in sync with the current UIkit version, and the recent jump to UIkit 3 changed a lot of classes.

Unfortunately, the Sublime Package Control does not support installing older versions, as far as I know. However, you can manually go back to the 1.13.0 release that still supports UIkit 2.

1. Remove existing plugin using package control.
2. On the terminal, run the following (paths need to be adapted if you are on something different than macOS):

    ```
    cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages
    git clone --branch 1.13.0 git@github.com:uikit/uikit-sublime.git
    ```
