### ISSUE TITLE
Conflic with other Packages?

### ISSUE THREAD

**Issue by Acturus** [uikit/uikit-sublime#5]
Hi, recently I installed the Uikit Autocomplete via Package Control but I dont recieve any suggestions, I followed the examples in GIFs with classes, data-atributes and setting the syntax with no result, also I reinstalled the plugin but the problem continues.
I think maybe other package disables the funtionality of the plugin. There is a list of my packages:
- Colorpicker
- Emmet (PyV8 included)
- Jquery
- Uikit Autocomplete

Any suggestions to solve this problem? I hope could help me.
Regards.

P.D. Sorry for the bad english, I´m learning, also I wanted to tell that... I love this framework! =) and I'm using it for the website of an event at my university. Thanks for developing it!

![packages](https://cloud.githubusercontent.com/assets/2430569/4190079/409c5f88-3782-11e4-9e29-d92e6b309005.jpg)

**Comment by florianletsch** [comment]
As I mentioned, there was a bug causing some issues with auto completion. That one is fixed in today's release v. 1.10.0
Please checkout that version and see if your issues persist.
