### ISSUE TITLE
New themes in Customizer not working

### ISSUE THREAD

**Issue by jerry1970** [uikit/uikit-sublime#8]
Selecting one of the new themes in the customizer (all except the Default, Almost Flat, and Gradient) does not work. The URLs result in 404s:
http://getuikit.com/custom/avenue/uikit-customizer.less
http://getuikit.com/custom/avenue/styles/blue/style.less
http://getuikit.com/custom/avenue/customizer.json

The URL for the Gradient, which works, looks like this:
http://getuikit.com/themes/gradient/uikit-customizer.less

**Comment by saschadube** [comment]
Thanks, it is fixed. Only the default, gradient and almost-flat theme are available.
